// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressController from "./address_controller"
application.register("address", AddressController)

import CardController from "./card_controller"
application.register("card", CardController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FormElementController from "./form_element_controller"
application.register("form-element", FormElementController)

import FormResetController from "./form_reset_controller"
application.register("form-reset", FormResetController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
