require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Rails/LexicallyScopedActionFilter:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20230304124900_devise_create_users.rb'
