require:
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Rails/LexicallyScopedActionFilter:
  Enabled: false
