default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV["POSTGRES_USER"] || Rails.application.credentials.database[:username] %>
  password: <%= ENV["POSTGRES_PASSWORD"] || Rails.application.credentials.database[:password] %>

development:
  <<: *default
  database: merchant_development

test:
  <<: *default
  database: merchant_test

production:
  <<: *default
  database: merchant_production
  username: merchant
  password: <%= ENV["MERCHANT_DATABASE_PASSWORD"] %>
